name: devops-governance

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.AZURE_PERSONAL_TOKEN }}

jobs:
  devops-governance-checks:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      
      - name: Get Branch Name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          else
            BRANCH_NAME="${GITHUB_REF_NAME}"
          fi

          echo "Branch: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"

      
      - name: Skip protected branches
        run: |
          echo "Checking if branch is protected: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" == "main" || \
                "$BRANCH_NAME" == f* ]]; then
            echo "✅ Protected branch detected. Skipping validation."
            exit 0
          fi


      - name: Validate branch name
        if: steps.branch_check.outputs.is_protected == 'false'
        run: |
          echo "Validating branch: $BRANCH_NAME"

          REGEX="^(feature|bugfix|chore)\/[A-Z]+-[0-9]+-.+$"

          if [[ ! "$BRANCH_NAME" =~ $REGEX ]]; then
            echo "Skipping validation for protected branch: $BRANCH_NAME"
            exit 0
          fi

          
          # Regex for allowed branch names
          REGEX="^(us[0-9]{6,}|r[0-9]{6,}|fb[0-9]{6,}|hb[0-9]{6,})(-tk[0-9]{6,})?(-[a-z0-9-]+)+$"

          if [[ "$BRANCH_NAME" =~ $REGEX ]]; then
            echo "✅ Branch: $BRANCH_NAME - Branch name valid"
          else
            echo "❌ Invalid Branch Name"
            echo "Branch: $BRANCH_NAME"
            echo "------------------------------------"
            echo "Sample valid formats:"
            echo "------------------------------------"
            echo "r654183-gbs-release"
            echo "fb452689-gbs-r5-enhancement"
            echo "hb487935-hotfix-changes"
            echo "us732187-new-claims"
            echo "us732187-tk740320-ct-edw-support-request"
            echo "------------------------------------"
            exit 1
          fi